#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys

from thrift.transport import TTransport


class ServiceErrorCode(object):
    No = 0
    DivByZero = 1

    _VALUES_TO_NAMES = {
        0: "No",
        1: "DivByZero",
    }

    _NAMES_TO_VALUES = {
        "No": 0,
        "DivByZero": 1,
    }
